### ISSUE TITLE
A question about candidates in GDA

### ISSUE THREAD

**Issue by mrluin** [JingyunLiang/RVRT#1]
Hello,

Thanks for your great work!

I have a question about `candidates` of GDA. I think candidates=9 means one position in Q should calculate correlation with 9 positions in K and V like what illustrated in Figure 3. Does it means the dimension of K/V should expand 9 times?

Looking forward to your reply, thanks!

**Comment by JingyunLiang** [comment]
Thanks for your question. It means K/V should be sampled for 9 times.

**Comment by mrluin** [comment]
Thanks for your quick reply. Sampling 9 times on K/V and performing 9 times attention for each Q, and then aggregation, right? Does it comsumes too much GPU memory?

**Comment by JingyunLiang** [comment]
The attention is used for aggregation. We wrote it with cuda, so the memory is controllable.

**Comment by mrluin** [comment]
Sorry for another question under the closed issue.

In ablation study, I notice that you give comparisons on different alignment methods, the improvement of GDA* is about 0.07db compared with DCN. And commonly, flow-guided deformable convolution is more stable and with better performance than DCN, so how about the performance if conducting attention on K/V which are aligned by flow-guided deformable convolution?

Thanks in advance.

**Comment by JingyunLiang** [comment]
I haven't trained that yet, but it looks too complex (not elegant) if we stack them together.
