### ISSUE TITLE
代码什么时候开源呢？

### ISSUE THREAD

**Issue by XIAJIUFAN** [JingyunLiang/RVRT#2]
大佬好，啥时候能开源代码呢？论文有些地方没明白，想结合代码来看

**Comment by caiyuanhao1998** [comment]
> 大佬好，啥时候能开源代码呢？论文有些地方没明白，想结合代码来看

Hi, 同学你好，你还在焦急等待吗？
我们的代码已经开源了，首个使用Transformer做视频去模糊和首个使用Sequence-to-Sequence做视频复原的工作，两个工作已经正式发表在ICML 2022上，欢迎来使用我们的代码。

https://github.com/linjing7/VR-Baseline
